# Num-Ex 예제
## 시퀀스 데이터로부터 배여생성

In [1]:
import numpy as np

In [9]:
data1 = [0,1,2,3,4,5]
a1 = np.array(data1)
a1

array([0, 1, 2, 3, 4, 5])

In [5]:
data2 = [0.5,1,2,3,4,5]
a1 = np.array(data2)
a1

array([0.5, 1. , 2. , 3. , 4. , 5. ])

In [7]:
np.array([[0.5],[2],[0.001],[8]])

array([[5.e-01],
       [2.e+00],
       [1.e-03],
       [8.e+00]])

In [8]:
np.array([[1,2,3],[4,5,6],[7,8,9]])

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

# #범위를 지정해 배열 생성

1. arr_obj = np.arange([strat, ], stop[, step])
 - start부터 stop전까지 steop만큼 더해 배열을 생성
 - start 디폴트는 0
 - step 디포르는 1

In [11]:
np.arange(0, 10, 2)

array([0, 2, 4, 6, 8])

In [12]:
np.arange(1,10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [13]:
np.arange(5)

array([0, 1, 2, 3, 4])

In [14]:
a1 = np.arange(1,10)
a1.shape #데이터 타입이 튜플이라는 뜻 (9,) 컴마가 붙음

(9,)

In [15]:
a2 = np.array([[1,2,3],[4,5,6],[7,8,9]])
a2.shape#2차원배열 3*3 이라서 3 3

(3, 3)

In [16]:
a1 = np.arange(1,10)
a1.reshape(3,3)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [17]:
np.arange(12).reshape(4,3)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [19]:
b1 = np.arange(12).reshape(4,3)
b1.shape

(4, 3)

In [22]:
b2 = np.arange(5)
b2.shape

(5,)

## 범위를 지정해 배열생성

범위내 숫자를 똑같은 값의 증가량을 가지게 반복해서 프린트하게 함
(최소값, 최댓값, 반복회수)

In [25]:
np.linspace(1,10,10)

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [24]:
np.linspace(0, np.pi,10)

array([0.        , 0.34906585, 0.6981317 , 1.04719755, 1.3962634 ,
       1.74532925, 2.0943951 , 2.44346095, 2.7925268 , 3.14159265])

1. 특별한 형태의 배열 생성
 - arr_zero_n = np.zero(n)
 - arr_zero_mxn = np.zero((m,n)) : 원소가 0인 배열 생성
 - arr_one_n = np.ones(n)
 - arr_one_mxn = np.ones((m,n)) 원소가 1인 배열 생성

In [27]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [28]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [29]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [30]:
np.ones((3,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [33]:
np.zeros((3,4,3))

array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]])

arr_I = np.eye(n)
- n x n 단위 행열 생성
단위 행렬 = n x n 대각선으로 1이 들어가는 것을 단위 행렬이라고함

In [34]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

1. 배열의 데이터 타입 변경
 - arr_obj = np.astype(타입)
 - 배열을 지정한 타입으로 변경

In [36]:
np.array(['1.5','0.62', '2,', '3.14', '3.141592'])

array(['1.5', '0.62', '2,', '3.14', '3.141592'], dtype='<U8')

In [38]:
str_a1 = np.array(['1.5','0.62', '2.', '3.14', '3.141592'])
num_a1 = str_a1.astype(float)
num_a1

array([1.5     , 0.62    , 2.      , 3.14    , 3.141592])

In [39]:
str_a1.dtype

dtype('<U8')

In [41]:
num_a1.dtype

dtype('float64')

In [42]:
str_a2 = np.array(['1','3','5','7','9'])
num_a2 = str_a2.astype(int)
num_a2

array([1, 3, 5, 7, 9])

In [43]:
str_a2.dtype

dtype('<U1')

In [44]:
num_a2.dtype

dtype('int32')

# # 난수 배열의 생성

1. np.random.seed(시드값)
 - 난수 생성 시드 값 설정
2. rand_num = np.random.enad()
 - (0,1) 사이의 실수 난수 생성
3. rand_num = np.random.rand([d0, d1, .., ,dn])
 - 지정한 차원의 배열 생성
 - (0,1) 사이의 실수 난수로 채움
4. rand_num = np.random.randn([d0,d1,...,dn])
 - 지정한 차원의 배열 생성
 - 가우시안 표준 정규 분포를 따르는 실수 난수 채움
5. rand_num = np.random.randint([low], high,[size])
 - (low, high) 사이의 정수 난수를 갖는 배열 생성
 - size는 배열의 크기 - 튜플로 지정(d0,d1,..,dn)
 - low의 디폴트 값은 0

In [45]:
np.random.rand(2,3)

array([[0.10341227, 0.83684181, 0.24096045],
       [0.01807565, 0.09983415, 0.78682354]])

In [46]:
np.random.rand()

0.44763484817021426

In [47]:
np.random.rand(2,3,4)

array([[[0.37454427, 0.90941497, 0.30319601, 0.12898349],
        [0.77337481, 0.01313557, 0.61469067, 0.97003286],
        [0.06348186, 0.317684  , 0.30810224, 0.86262402]],

       [[0.7350609 , 0.62940467, 0.97881101, 0.52243387],
        [0.49466383, 0.21634218, 0.81441875, 0.0073317 ],
        [0.84310744, 0.35790733, 0.17703247, 0.71055966]]])

In [49]:
np.random.randint(10, size=(3,4))

array([[2, 4, 9, 8],
       [1, 7, 9, 7],
       [1, 9, 7, 8]])

In [50]:
np.random.randint(1,30)

5

## 배열의 연산


In [51]:
arr = np.array([10,20,30,40])
arr2 = np.array([1,2,3,4])
arr+arr2

array([11, 22, 33, 44])

In [53]:
arr-arr2

array([ 9, 18, 27, 36])

In [54]:
arr2 * 2 #배열의 모든 요소 를 곱해라

array([2, 4, 6, 8])

In [55]:
arr2 ** 2 

array([ 1,  4,  9, 16], dtype=int32)

In [57]:
arr * arr2

array([ 10,  40,  90, 160])

In [58]:
arr / arr2

array([10., 10., 10., 10.])

In [59]:
arr / (arr2**2)

array([10.        ,  5.        ,  3.33333333,  2.5       ])

In [60]:
arr > 20

array([False, False,  True,  True])

# # 통계를 위한 연산

In [62]:
arr3 = np.arange(5)
arr3

array([0, 1, 2, 3, 4])

In [64]:
[arr3.sum(), arr3.mean()]

[10, 2.0]

# # 배열의 인덱싱과 슬라이싱

1. 뱅열의 인덱싱
 - 배열명[위치]
 - 배열명[[위치1,위치2,..., 위치n]]
  -해당차원의 여러 원소 선택
 - 배열명[행_위치, 열_위치]
 - 배열명[[행_위치1, 행_위치2,..., 행_위치n],
            [열_위치1, 열_위치2,...,열_위치n]]
 - 2차원 배열의 여러 원소 선택
 - 배열명[조건식] : 해당 조건식을 만족하는 원소만 선택

In [65]:
a1 = np.array([0,10,20,30,40,50])
a1

array([ 0, 10, 20, 30, 40, 50])

In [66]:
a1[0]

0

In [67]:
a1[4]

40

In [68]:
a1[5] =70
a1

array([ 0, 10, 20, 30, 40, 70])

In [69]:
a1[[1,3,4]]

array([10, 30, 40])

In [72]:
a2 = np.arange(10,100,10).reshape(3,3)
a2

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

In [74]:
a2[0,2]

30

In [75]:
a2[2,2] = 95
a2

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 95]])

In [76]:
a2[1]

array([40, 50, 60])

In [77]:
a2[1] = np.array([45,55,65])
a2

array([[10, 20, 30],
       [45, 55, 65],
       [70, 80, 95]])

In [79]:
a2[1] = [47,57,67]
a2

array([[10, 20, 30],
       [47, 57, 67],
       [70, 80, 95]])

In [80]:
a2[[0,2],[0,1]]

array([10, 80])

In [81]:
a = np.array([1,2,3,4,5,6])
a[a>3]

array([4, 5, 6])

In [83]:
a[(a%2) == 0]

array([2, 4, 6])

## 배열의 슬라이싱


1. 배열[시작_위치:끝_위치]
 - 시작위치 ~끝위치 -1 범위의 슬라이싱
 - 시작_위치 생략시 0
 - 끝_위치 생략시 배열의 끝
 
2. 배열[행시작_위치:행끝_위치,열시작위치,: 열끝위치]
 2 차원 슬라이싱

In [84]:
b1 = np.array([0,10,20,30,40,50])
b1[1:4]


array([10, 20, 30])

In [85]:
b1[:3]

array([ 0, 10, 20])

In [87]:
b1[2:]

array([20, 30, 40, 50])

In [88]:
b1[2:5] = np.array([25,35,45])
b1

array([ 0, 10, 25, 35, 45, 50])

In [89]:
b1[3:6] =60
b1

array([ 0, 10, 25, 60, 60, 60])

In [90]:
b2 = np.arange(10,100,10).reshape(3,3)
b2

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

In [91]:
b2[1:3,1:3]

array([[50, 60],
       [80, 90]])

In [92]:
b2[:3, 1:]

array([[20, 30],
       [50, 60],
       [80, 90]])

In [93]:
b2[1][0:2]

array([40, 50])

In [95]:
b2[0:2, 1:3] = np.array([[25,35],[55,65]])
b2

array([[10, 25, 35],
       [40, 55, 65],
       [70, 80, 90]])